# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Vanna/Desktop/CarPark/RAMsim/cores/RAM_DEPTH128_WIDTH40/RAM_DEPTH128_WIDTH40.xci
# IP: The module: 'RAM_DEPTH128_WIDTH40' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Vanna/Desktop/CarPark/RAMsim/cores/RAM_DEPTH128_WIDTH40/RAM_DEPTH128_WIDTH40_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_DEPTH128_WIDTH40'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Vanna/Desktop/CarPark/RAMsim/cores/RAM_DEPTH128_WIDTH40/RAM_DEPTH128_WIDTH40.xci
# IP: The module: 'RAM_DEPTH128_WIDTH40' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Vanna/Desktop/CarPark/RAMsim/cores/RAM_DEPTH128_WIDTH40/RAM_DEPTH128_WIDTH40_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_DEPTH128_WIDTH40'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
